hand_ee_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - grip_1
    - grip_2
  gains:
    grip_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grip_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
robot_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - link_2
    - link_3
    - link_4
    - link_5
    - link_6
    - link_7
  gains:
    link_2:
      p: 100
      d: 1
      i: 10
      i_clamp: 1
    link_3:
      p: 100
      d: 1
      i: 10
      i_clamp: 1
    link_4:
      p: 100
      d: 1
      i: 10
      i_clamp: 1
    link_5:
      p: 100
      d: 1
      i: 10
      i_clamp: 1
    link_6:
      p: 100
      d: 1
      i: 10
      i_clamp: 1
    link_7:
      p: 100
      d: 1
      i: 10
      i_clamp: 1